### PR TITLE
Use Keyboard(Special)EventCallback internally

### PR DESCRIPTION
**Pull request by nanoant**
Otherwise it will crash on 10.9.

Please note that 1.6.9 is blacklisted by Apple at 10.9. Also in my forked repository there are some other minor changes and binary build for 1.7.0.

### CODE REVIEW

**Comment by mbaltaks** [comment]
Thanks very much for providing this patch, I'll get a 10.9 compatible build released asap.

**Comment by tylerstillwater** [comment]
Does this patch work for only 10.9? Or is it compatible with 10.8 and below?

**Comment by nanoant** [comment]
@mbaltaks Please do not update yet, I've found an issue on 10.9 that DoubleCommand hooks no longer work after waking Mac from sleep or hibernation, probably `IOSystem` releases `IOKeyboard` and re-opens it again on wake, but `DoubleCommand` does not update hooks then. I'll try to fix it tomorrow.

@tylerb It should work >= 10.6, but I will test it on VM to make sure.

**Comment by nanoant** [comment]
@mbaltaks False alarm! Seems that there was some `.log` file remaining (after my 1st attempts to fix 10.9 problem) that made `DoubleCommand` to refuse to start. However removing that file makes it work after wake just fine.

So you're free to go with official build :>

@tylerb Just tested on `10.6` VM, it works well.

**Comment by nanoant** [comment]
@mbaltaks If you're on 10.9 and Xcode 5 you won't be able to build 32-bit driver with new Clang 5 toolchain that does not support 32-bit `-fapple-kext`, you need to switch to LLVM GCC from Xcode 4.6.

**Comment by nanoant** [comment]
@tylerb Just updated build for 32-bit 10.6 at https://github.com/nanoant/doublecommand/releases/tag/Release-1.7.0, please try.

**Comment by tylerstillwater** [comment]
Works great! Thanks! :)

**Comment by mbaltaks** [comment]
Thanks again for the patch Adam, I've released a new build on the main page, and linked to your fork with credit for the fix.

**Pull request merged**
